spring:
  datasource:
  url: jdbc:h2:tcp://localhost/~/h2DB/querydsl
  username: sa
  password:
  driver-class-name: org.h2.Driver

jpa:
  hibernate:
    ddl-auto: create
  properties:
    hibernate:
      # system.out
#      show_sql: true
      format_sql: true
      use_sql_comments: true

# logger로 query 출력
logging.level:
  org.hibernate.SQL: debug
#  org.hibernate.type: trace